//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarritoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito
    {
        public int nroFactura { get; set; }
        public int nroItem { get; set; }
        public int codProd { get; set; }
        public int cantProd { get; set; }
    
        public virtual facturas facturas { get; set; }
        public virtual productos productos { get; set; }
    }
}
